sudo: false
language: python

matrix:
  include:
    - python: '2.7'
      env: TOX_ENV=py27-django18
    - python: '2.7'
      env: TOX_ENV=py27-django19
    - python: '2.7'
      env: TOX_ENV=py27-django110
    - python: '2.7'
      env: TOX_ENV=py27-django111
    - python: '3.5'
      env: TOX_ENV=py35-django18
    - python: '3.5'
      env: TOX_ENV=py35-django19
    - python: '3.5'
      env: TOX_ENV=py35-django110
    - python: '3.5'
      env: TOX_ENV=py35-django111
    - python: '3.5'
      env: TOX_ENV=py35-django20
    - python: '3.6'
      env: TOX_ENV=py36-django18
    - python: '3.6'
      env: TOX_ENV=py36-django19
    - python: '3.6'
      env: TOX_ENV=py36-django110
    - python: '3.6'
      env: TOX_ENV=py36-django111
    - python: '3.6'
      env: TOX_ENV=py36-django20
    - python: '3.6'
      env: TOX_ENV=isort
    - python: '3.6'
      env: TOX_ENV=docs
    - python: '3.6'
      env: TOX_ENV=pre_commit

before_install:
  - if [[ "$TOX_ENV" == py* ]]; then pip install codecov; fi

install:
  - pip install tox

after_success:
  - if [[ "$TOX_ENV" == py* ]]; then codecov; fi

script:
  - tox -e $TOX_ENV
