# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-24 08:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_route", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Description for router", null=True
            ),
        ),
    ]
