name: test
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
        toxenv:
          - 'django32'
          - 'django40'
          - 'django41'
        include:
          - python-version: '3.6'
            toxenv: 'django32'
            os: [ubuntu-latest]
          - python-version: '3.7'
            toxenv: 'django32'
            os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and upgrade packaging tools
      run: python -m pip install --upgrade pip codecov tox
    - name: Run tests
      run: tox
      env:
        TOXENV: ${{ matrix.toxenv }}
    - name: Upload coverage report
      run: codecov
